Tickets = new Mongo.Collection("ticket");
Sms = new Mongo.Collection("sms");
TicketActivities = new Mongo.Collection("ticketactivity");
TicketRatings = new Mongo.Collection("ticketrating");
Clients = new Mongo.Collection("client");
Staffs = new Mongo.Collection("staff");
Services = new Mongo.Collection("service");
MySessions = new Mongo.Collection("session");
Schemas = {};